<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/styles.css">

    <title>Documentation</title>
</head>

<body style="background:#F7F7F7">
    <div class="container">
        <h1 class="center">How to view the examples!</h1>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Step 1 <span style="float: right;color: #fe5d5d;">This is an important step</span> </h5>
                <hr>
                <p class="heading">
                    Create your Database using the link below<br>
                    <span class="summary">This page generates a <b>config.php</b> file in <b>controllers</b> folder. This step is required to link your Database</span>
                </p>
                <p class="note">Note: If you've already created you database, just specify the name</p>
                <a href="create_db.php" target="_blank" class="btn btn-link">Create Database</a>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Step 2</h5>
                <hr>
                <p class="heading">
                    Create account<br>
                    <span class="summary">This page is example of <b>insert</b> operation<br>
                        The data gets inserted to your database
                    </span>
                </p>
                <p class="note">Note: Tables and fileds gets autogenerated</p>
                <a href="create_acc.php" target="_blank" class="btn btn-link">Create Account</a>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Step 3</h5>
                <hr>
                <p class="heading">
                    Login<br>
                    <span class="summary">This page is example of how to fetch data from your database and validate if that perticular user exists<br>
                    </span>
                </p>
                <p class="note">Note: Usage of sessions is also shown in this</p>
                <a href="login.php" class="btn btn-link" target="_blank">Login</a>
            </div>
        </div>
        <div style="padding: 15px;">
            <h5>To learn how to implement these functions in your project, <a href="#" class="btn btn-link">Click here</a></h5>
        </div>

    </div>

</body>

</html>